"""auto migration

Revision ID: 9465b47bcad2
Revises: 1fdd479a949d
Create Date: 2025-12-06 11:48:09.105113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9465b47bcad2'
down_revision: Union[str, Sequence[str], None] = '1fdd479a949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_events', sa.Column('pin_state', sa.Boolean(), nullable=False))
    op.add_column('device_events', sa.Column('trigger_reason', sa.String(), nullable=True))
    op.add_column('device_events', sa.Column('power_kw', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('device_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('device_events', 'active_power')
    op.alter_column('inverter_power_records', 'active_power',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverter_power_records', 'active_power',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('device_events', sa.Column('active_power', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('device_events', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('device_events', 'power_kw')
    op.drop_column('device_events', 'trigger_reason')
    op.drop_column('device_events', 'pin_state')
    # ### end Alembic commands ###
